name: React-CI
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        working-directory: frontend
        run: npm install
        
      - name: Run Lint
        working-directory: frontend
        run: npm run lint

      - name: Run Tests
        working-directory: frontend
        run: npm run test  

      - name: Build
        working-directory: frontend
        run: npm run build